# TP3 : Programmation Dynamique

## Question 1
La programmation dynamique consiste en la réslution de problèmes de tailles inférieures et l'utilisation des résultats. La reation de récurrence permet de trouver les paramètres des sous-problèmes et de rassembler les résultats. On suppose donc que toute sous-solution d'une solution optimale est une solution optimale du sous-problème.

In [4]:
function readKnaptxtInstance(filename)
    price=Int64[]
    weight=Int64[]
    KnapCap=Int64[]
    open(filename) do f
        for i in 1:3
            tok = split(readline(f))
            if(tok[1] == "ListPrices=")
                for i in 2:(length(tok)-1)
                    push!(price,parse(Int64, tok[i]))
                end
            elseif(tok[1] == "ListWeights=")
                for i in 2:(length(tok)-1)
                    push!(weight,parse(Int64, tok[i]))
                end
            elseif(tok[1] == "Capacity=")
                push!(KnapCap, parse(Int64, tok[2]))
            else
                println("Unknown read :", tok)
            end
        end
    end
    capacity=KnapCap[1]
    return price, weight, capacity
end

readKnaptxtInstance (generic function with 1 method)

In [72]:
filename = "../InstancesKnapSack/test.opb.txt"

v, w, Q = readKnaptxtInstance(filename)
n = length(v)

C = zeros(Q+1,n+1)

C[1,:] = zeros(n+1)
# C[j,i]: val max qu'on peut porter si poids capacité est j-1
# et qu'on a que objets de  1 à i de dispo

for i = 2:n+1
    for j = 2:Q+1
        if w[i-1] <= j-1 # on peut rentrer l'objet i-1
            C1 = C[j-w[i-1], i-1] + v[i-1] # on prend l'objet i-1
            C2 = C[j, i-1]
            
            if (C1 > C2)
                # on a pris l'objet i-1
                C[j,i] = C1
                # solution du pb de taille j-w[i-1]-1
                # avec l'objet i-1 en plus
            else
                # on n'a pas pris l'objet i-1
                C[j,i] = C2
            end 
        else  # pas la place pour l'objet i-1
            C[j,i] = C[j, i-1]
        end
    end
end

A = []

val_max = C[end,end]
j = Q
for i in n:-1:1
    if C[j+1,i+1] != C[j+1,i]
        push!(A,i)
        j = j - w[i]
    end
end

display(C)
display(A)

11×5 Matrix{Float64}:
 0.0   0.0   0.0   0.0   0.0
 0.0   0.0   0.0   0.0   0.0
 0.0   0.0   0.0   0.0   0.0
 0.0   0.0   0.0  12.0  12.0
 0.0   0.0  40.0  40.0  40.0
 0.0   0.0  40.0  40.0  40.0
 0.0   0.0  40.0  40.0  40.0
 0.0  42.0  42.0  52.0  52.0
 0.0  42.0  42.0  52.0  52.0
 0.0  42.0  42.0  52.0  65.0
 0.0  42.0  42.0  54.0  65.0

2-element Vector{Any}:
 4
 2

In [71]:
filename = "../InstancesKnapSack/test.opb.txt"

v, w, Q = readKnaptxtInstance(filename)
n = length(v)

C = zeros(Q+1,n+1)

C[1,:] = zeros(n+1)
# C[j,i]: val max qu'on peut porter si poids capacité est j-1
# et qu'on a que objets de  1 à i de dispo

A = zeros(Q+1,n)
# A[j]: liste de 0/1 solution du pb avec capacité j-1
for j = 2:Q+1
for i = 2:n+1
    
        if w[i-1] <= j-1 # on peut rentrer l'objet i-1
            C1 = C[j-w[i-1], i-1] + v[i-1] # on prend l'objet i-1
            C2 = C[j, i-1]
            
            if (C1 > C2)
                # on a pris l'objet i-1
                C[j,i] = C1
                # solution du pb de taille j-w[i-1]-1
                # avec l'objet i-1 en plus
                A[j] = copy(A[j-w[i-1]])
                A[j,i-1] = 1
            else
                # on n'a pas pris l'objet i-1
                C[j,i] = C2
                A[j] = copy(A[j-w[i-1]])
                
            end 
        else  # pas la place pour l'objet i-1
            C[j,i] = C[j, i-1]
            A[j] = copy(A[j-1])
        end
    end
end

display(C)
display(A)

11×5 Matrix{Float64}:
 0.0   0.0   0.0   0.0   0.0
 0.0   0.0   0.0   0.0   0.0
 0.0   0.0   0.0   0.0   0.0
 0.0   0.0   0.0  12.0  12.0
 0.0   0.0  40.0  40.0  40.0
 0.0   0.0  40.0  40.0  40.0
 0.0   0.0  40.0  40.0  40.0
 0.0  42.0  42.0  52.0  52.0
 0.0  42.0  42.0  52.0  52.0
 0.0  42.0  42.0  52.0  65.0
 0.0  42.0  42.0  54.0  65.0

11×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  1.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  1.0  1.0
 0.0  0.0  1.0  1.0

In [68]:
filename = "../InstancesKnapSack/test.opb.txt"

v, w, Q = readKnaptxtInstance(filename)
n = length(v)

C = zeros(Q+1,n+1)

C[1,:] = zeros(n+1)
# C[j,i]: val max qu'on peut porter si poids capacité est j-1
# et qu'on a que objets de  1 à i de dispo

A = [
    [],[],[],[],[],[],[],[],[],[],[]
]
println(A)

for i = 2:n+1
    for j = 2:Q+1
        if w[i-1] <= j-1 # on peut rentrer l'objet i-1
            C1 = C[j-w[i-1], i-1] + v[i-1] # on prend l'objet i-1
            C2 = C[j, i-1]
            
            if (C1 > C2)
                # on a pris l'objet i-1
                C[j,i] = C1
                # solution du pb de taille j-w[i-1]-1
                # avec l'objet i-1 en plus
                A[j] = copy(A[j-w[i-1]])
                push!(A[j], i-1)
                display(A[j])
            else
                # on n'a pas pris l'objet i-1
                C[j,i] = C2
                A[j] = copy(A[j])
            end 
        else  # pas la place pour l'objet i-1
            C[j,i] = C[j, i-1]
            A[j] = copy(A[j-1])
        end
    end
end

display(C)
display(A)

Vector{Any}[[], [], [], [], [], [], [], [], [], [], []]


1-element Vector{Any}:
 1

1-element Vector{Any}:
 1

1-element Vector{Any}:
 1

1-element Vector{Any}:
 1

1-element Vector{Any}:
 2

1-element Vector{Any}:
 2

1-element Vector{Any}:
 2

1-element Vector{Any}:
 3

2-element Vector{Any}:
 2
 3

2-element Vector{Any}:
 2
 3

2-element Vector{Any}:
 2
 3

3-element Vector{Any}:
 2
 3
 3

1-element Vector{Any}:
 4

2-element Vector{Any}:
 2
 4

11×5 Matrix{Float64}:
 0.0   0.0   0.0   0.0   0.0
 0.0   0.0   0.0   0.0   0.0
 0.0   0.0   0.0   0.0   0.0
 0.0   0.0   0.0  12.0  12.0
 0.0   0.0  40.0  40.0  40.0
 0.0   0.0  40.0  40.0  40.0
 0.0   0.0  40.0  40.0  40.0
 0.0  42.0  42.0  52.0  52.0
 0.0  42.0  42.0  52.0  52.0
 0.0  42.0  42.0  52.0  65.0
 0.0  42.0  42.0  54.0  65.0

11-element Vector{Vector{Any}}:
 []
 []
 []
 []
 []
 [2]
 [2]
 [2, 3]
 [2, 3]
 [4]
 [2, 4]